version: 0.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
install:
- cmd: >-
    curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe

    dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log
build_script:
- cmd: >-
    dotnet restore src\GdaxApi\GdaxApi.sln

    dotnet pack src\GdaxApi\GdaxApi\GdaxApi.csproj -o artifacts\packages -c Release
test: off
artifacts:
- path: src\GdaxApi\GdaxApi\artifacts\packages\*.nupkg
- path: src\GdaxApi\GdaxApi\artifacts\tests\*
deploy: off